### ISSUE TITLE
Fix: crash al abrir un stored location

### ISSUE THREAD

**Issue by ImanolOlveira** [carlos-mg89/flickrgallery#103]

**Comment by ImanolOlveira** [comment]
java.lang.IllegalStateException: Counter has been corrupted! counterVal=-1
        at androidx.test.espresso.idling.CountingIdlingResource.decrement(CountingIdlingResource.java:186)
        at EspressoIdlingResource.decrement(EspressoIdlingResource.kt:13)
        at com.example.flickrgallery.ui.explore.ExploreBindingAdapterKt.setItems(ExploreBindingAdapter.kt:15)
